#!/usr/bin/env python3
"""
Test script to simulate a Slack message without actually sending it.
This shows you exactly how the message will be formatted in Slack.
"""

import json
from datetime import datetime
import pytz

def create_sample_message():
    """Create a sample Gmail message for testing."""
    return {
        'id': 'test_message_123',
        'subject': '🚨 Forth System Alert - High CPU Usage',
        'sender': 'alerts@forth.com',
        'date': '2024-01-15 14:30:25 Asia/Manila',
        'body': 'The Forth monitoring system has detected high CPU usage on server web-01. Current CPU usage is at 95% which exceeds the threshold of 80%. Please investigate immediately.\n\nServer Details:\n- Hostname: web-01.forth.com\n- IP: 192.168.1.100\n- Load Average: 4.2, 3.8, 2.1\n\nThis alert was generated by the Forth monitoring system.',
        'thread_id': 'thread_abc123',
        'snippet': 'The Forth monitoring system has detected high CPU usage on server web-01...'
    }

def create_slack_payload(message_data, gmail_query="from:noreply@forthcrm.com (subject:\"Cancellation\" OR subject:\"Cancel\" OR subject:\"cancelled\" OR subject:\"cancelled\") newer_than:7d"):
    """Create the Slack payload that would be sent."""
    
    # Create Gmail link
    gmail_link = f"https://mail.google.com/mail/u/0/#inbox/{message_data['thread_id']}"
    
    # Format message
    text = f"📧 New Email: {message_data['subject']}"
    
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"📧 {message_data['subject']}"
            }
        },
        {
            "type": "section",
            "fields": [
                {
                    "type": "mrkdwn",
                    "text": f"*From:*\n{message_data['sender']}"
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Date:*\n{message_data['date']}"
                }
            ]
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Query:* `{gmail_query}`"
            }
        }
    ]
    
    # Add body preview
    if message_data['body']:
        # Truncate body if too long
        body_preview = message_data['body']
        if len(body_preview) > 200:
            body_preview = body_preview[:200] + "..."
        
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Preview:*\n```{body_preview}```"
            }
        })
    
    # Add Gmail button
    blocks.append({
        "type": "actions",
        "elements": [
            {
                "type": "button",
                "text": {
                    "type": "plain_text",
                    "text": "Open in Gmail"
                },
                "url": gmail_link,
                "action_id": "open_gmail"
            }
        ]
    })
    
    payload = {
        "channel": "forth-alerts",
        "username": "Gmail Monitor",
        "text": text,
        "blocks": blocks
    }
    
    return payload

def display_slack_message(payload):
    """Display the Slack message in a readable format."""
    print("🔔 SLACK MESSAGE PREVIEW")
    print("=" * 60)
    print(f"Channel: {payload['channel']}")
    print(f"Username: {payload['username']}")
    print(f"Text: {payload['text']}")
    print("\n📋 BLOCKS STRUCTURE:")
    print("-" * 40)
    
    for i, block in enumerate(payload['blocks'], 1):
        print(f"\nBlock {i}: {block['type'].upper()}")
        
        if block['type'] == 'header':
            print(f"  📝 Header Text: {block['text']['text']}")
            
        elif block['type'] == 'section':
            if 'fields' in block:
                print("  📊 Fields:")
                for field in block['fields']:
                    print(f"    • {field['text']}")
            elif 'text' in block:
                print(f"  📝 Text: {block['text']['text']}")
                
        elif block['type'] == 'actions':
            print("  🔘 Actions:")
            for element in block['elements']:
                print(f"    • Button: {element['text']['text']}")
                print(f"      URL: {element['url']}")

def display_json_payload(payload):
    """Display the raw JSON payload."""
    print("\n🔧 RAW JSON PAYLOAD:")
    print("=" * 60)
    print(json.dumps(payload, indent=2))

def main():
    """Main function to run the test."""
    print("🧪 Gmail → Slack Message Simulator")
    print("This shows how your Forth emails will appear in Slack\n")
    
    # Create sample message
    sample_message = create_sample_message()
    
    # Create Slack payload
    slack_payload = create_slack_payload(sample_message)
    
    # Display the message
    display_slack_message(slack_payload)
    
    # Display raw JSON
    display_json_payload(slack_payload)
    
    print("\n✅ This is exactly how your Forth emails will appear in Slack!")
    print("📧 The message includes:")
    print("   • Header with email subject")
    print("   • From and Date fields")
    print("   • Gmail query used")
    print("   • Email body preview (truncated if long)")
    print("   • 'Open in Gmail' button")
    
    print("\n🔗 Gmail Link Preview:")
    print(f"   https://mail.google.com/mail/u/0/#inbox/{sample_message['thread_id']}")

if __name__ == "__main__":
    main()

